Ajout fonctionnalité verrouillage positionnement du BL
sanjuant/LaCalvBattleLogs pull request #32
Opened 2023-11-02 12:43 UTC by kerluc

Ajout d'une fonctionnalité pour verrouiller la disposition du BL pour pouvoir continuer de voir les infos (par exemple en opacité réduite) mais de pouvoir interagir avec l'UI derrière du jeu sans déplacer le log dans tous les sens

2023-11-02 17:13 UTC, sanjuant requested changes
Merci pour cette PR de qualité !

2023-11-02 17:13 UTC, sanjuant commented on battlelogs.css
> +    pointer-events: initial;
Top, je ne connaissais pas cette propriété. Tu peux aussi ajouter pointer-events sur les boutons du battlelogs-locked, que l'on puisse toujours interagir avec les autres boutons ?

```js
#Menu-Position.open.battlelogs-locked button {
    pointer-events: initial;
}

```
Et c'est possible d'autoriser le scroll ?

2023-11-02 17:33 UTC, kerluc commented on battlelogs.css
> +    pointer-events: initial;
Je regarde ça dès que possible

Pour le scroll, je vais voir ce qu'il est possible de faire, je te promet rien, il se peut que ça pose probleme.
pointer-events désactive tous les evenements de la souris sur l'élément (c'est pour ça que je le reset spécifiquement sur le bouton atm)

2023-11-03 00:00 UTC, sanjuant commented on battlelogs.css
> +    pointer-events: initial;
Pour le scroll, il y aurait pas moyen d'activer le pointer-events si on détecte un scroll sur la souris et que l'on se trouve sur la zone du battle logs, avec un timeout ? Ou sinon peux être moins évident a faire, mais détecter le scroll de la même façon et ensuite scroller l'élément.

2023-11-04 11:17 UTC, kerluc commented on battlelogs.css
> +    pointer-events: initial;
Voilà, tu me dira si ca te convient, le comportement "lock" est fixé uniquement sur les vues qui n'ont pas la classe "unlocked" (donc que messages atm). 

Je pense qu'on est arrivé à un bon compromis là

2023-11-04 17:02 UTC, sanjuant approved these changes
On pourrait encore améliorer la zone de scroll, nottament pour le hover des boutons supprimer. Tu penses qu'il se passerait quoi si on définissait une div qui prend 100% de hauteur du wrapper, aligné a droite sur quelques pixel avec le pointer-events. Puis les type-label en z-index plus élevé que cette div ?

2023-11-04 17:02 UTC, merged

2023-11-04 17:17 UTC, kerluc commented
Comme je te l'ai expliqué pointer-events:none désactive complètement la capture des events sur les elements sur lesquels il s'applique (scrolls, onclick, etc.) . 

D'instinct, je te dirai que la div qui prend toute la hauteur avec les boutons au dessus (le tout avec pointer-events:initial) est une solution qui fonctionne aussi. Après je voulais éviter de rajouter trop de complexité pour le moment dans le layout pour un bouton mais c'est à garder dans un coin de la tête